# Use postgres/example user/password credentials
version: '3.1'

services:
  backend:
    image: vzlomed/hotlinebackend:latest
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - redis_prod
      - postgres_prod
  frontend:
    image: vzlomed/hotlinefrontend:latest
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - backend
  postgres_prod:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT_PROD}:5432
    volumes:
      - /data/hotlinetrade/postgres_data_production:/bitnami/postgresql
    networks:
      - app_network
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USR_PROD}
      - POSTGRESQL_PASSWORD=${POSTGRES_PWD_PROD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB_PROD}

      - POSTGRESQL_TIMEZONE=Europe/Moscow
  postgres_dev:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT_DEV}:5432
    volumes:
      - /data/hotlinetrade/postgres_data_development:/bitnami/postgresql
    networks:
      - app_network
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USR_DEV}
      - POSTGRESQL_PASSWORD=${POSTGRES_PWD_DEV}
      - POSTGRESQL_DATABASE=${POSTGRES_DB_DEV}

      - POSTGRESQL_TIMEZONE=Europe/Moscow
  redis_prod:
    image: bitnami/redis:latest
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - "${REDIS_PORT_PROD}:6379"
    volumes:
      - /data/hotlinetrade/redis_data_production:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PWD_PROD}
  redis_dev:
    image: bitnami/redis:latest
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - "${REDIS_PORT_DEV}:6379"
    volumes:
      - /data/hotlinetrade/redis_data_development:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PWD_DEV}
  pgpanel:
    image: dpage/pgadmin4
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - /data/hotlinetrade/pgpanel:/var/lib/pgadmin
    environment:
      - PROXY_X_FOR_COUNT = 1
      - PROXY_X_PROTO_COUNT = 0
      - PROXY_X_HOST_COUNT = 0
      - PROXY_X_PORT_COUNT = 1
      - PROXY_X_PREFIX_COUNT = 0
      - PGADMIN_DEFAULT_EMAIL=${POSTGRESPANEL_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRESPANEL_PWD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80
networks:
  app_network:
    driver: bridge
