# Use postgres/example user/password credentials
version: '3.1'

services:
  backend:
    image: vzlomed/hotlinebackend:latest
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
  frontend:
    image: vzlomed/hotlinefrontend:latest
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - backend
  postgres:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /data/hotlinetrade/postgres_data:/bitnami/postgresql
    networks:
      - app_network
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USR}
      - POSTGRESQL_PASSWORD=${POSTGRES_PWD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}

      - POSTGRESQL_TIMEZONE=Europe/Moscow
  redis:
    image: bitnami/redis:latest
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - /data/hotlinetrade/redis_data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PWD}
  pgpanel:
    image: dpage/pgadmin4
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - /data/hotlinetrade/pgpanel:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRESPANEL_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRESPANEL_PWD}
      - PGADMIN_LISTEN_PORT=80

      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False

    ports:
      - 5050:80
networks:
  app_network:
    driver: bridge
