version: '3.1'

services:
  backend:
    image: vzlomed/hotlinebackend:latest
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - bullboard
    ports:
      - ${BACKEND_PORT}:5000
#   frontend:
#     image: vzlomed/hotlinefrontend:latest
#     networks:
#       - app_network
#     restart: unless-stopped
#     depends_on:
#       - backend
#       - minio
  postgres:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - /data/hotlinetrade/postgres_data:/bitnami/postgresql
    networks:
      - app_network
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USR}
      - POSTGRESQL_PASSWORD=${POSTGRES_PWD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}

      - POSTGRESQL_TIMEZONE=Europe/Moscow
  redis:
    image: bitnami/redis:latest
    networks:
      - app_network
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - /data/hotlinetrade/redis_data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PWD}
  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - 9000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PWD}
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
    depends_on:
      - redis

networks:
  app_network:
    driver: bridge
